travis:
  secure:
    BINSTAR_TOKEN: Yio6j3euU6T/j0z0cAZu0A/K2zlJr85GZh3BKexqw2uh7xObHpe20oJzPsnyN8V/NUuda9gRMW6q4E3+gLI0dwab0e84OiGEiGadhN/R3TnLozUTwLN1rLCZZ0g5Gc2zTeL6LD/WWisz4zxkZsU2SWFcCa9moH1qgv/zyF4d3bLfSd9i3mIhJ7JYGtn6rmzPHZkzUYEnJiEZDNG0uD2kzq2AJ+RGpiJGFWJnvQCk0t9FSUIRFhUVlX+bxIyG8ZWZReRzlL0hohSyHv+MxLWGebIl6m4zACLYog/5pABXfaqin7270qhNK/PiwwBxnsypEBbCSLuVXIrnLvDq5wES0ILXG0NiRc6bqkan8peQQb9fFRxzkm3HEcHfyVdkR0yWMzI2COyfszXWT0F8jvfgjeBTw1472p9XH9HfGrwyZW6KkDXTlzsGc/YXX80kJdSxkw45Nh9Zk6ki1IhMVDuqPRtiPZK5/O+NqYQAwgkIjHkIQNkMG8A601wON2dm8UU4TRwhBy4KQ44psCXoatBdGO3FDQksSRJqgvEx9q3YiSm+cyNS7MngBbShpBUWyfjcNo+OOABPG/PTbEgMjCa4NjW34drNkr3SqMLzXlkYk+ptD5WfNSrNJvqopTVqP+Ia2mgyrYIulDwekjBdMx5xv/eaSE2vUjrN9Xxz/aqNFBo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
